debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.tw.project-board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mariadb://${DB_url}:${DB_port}/${DB_dataBaseName}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_name}
    password: ${DB_password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always
  data:
    rest:
      detection-strategy: annotated
      base-path: /api
  thymeleaf3:
    decoupled-logic: true


---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none